/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

/**
 *
 * @author felip
 */
public class TelaEquacao extends javax.swing.JFrame {

    /**
     * Creates new form TelaEquacao
     */
    public TelaEquacao() {
        initComponents();
        //lblEnunciadoB.setText("<html>x<sup>2</sup> + </html>");
        painelResultado.setVisible(false);
        //iniciando com valores 0 na equação
        //melhor sem o código abaixo para mostrar a formula no inicio do programa.
        /*
        lblNumeroA.setText(txtNumeroA.getValue().toString());
        lblNumeroB.setText(txtNumeroB.getValue().toString());
        lblNumeroC.setText(txtNumeroB.getValue().toString());
        */
        
        //lblFormulaB.setText("<html><sup>2</sup>-4.</html>");
        //lblDeltaResultado.setText("<html>&Delta; = </html>");
        //lblDeltaFormula.setText("<html>&Delta;=</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumeroA = new javax.swing.JSpinner();
        txtNumeroB = new javax.swing.JSpinner();
        txtNumeroC = new javax.swing.JSpinner();
        lblEnunciadoB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDeltaFormula = new javax.swing.JLabel();
        lblNumeroB = new javax.swing.JLabel();
        lblFormulaB = new javax.swing.JLabel();
        lblNumeroA = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblNumeroC = new javax.swing.JLabel();
        btnCalcularDelta = new javax.swing.JButton();
        painelResultado = new javax.swing.JPanel();
        lblDeltaResultado = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblDelta = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNumeroA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNumeroA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtNumeroAStateChanged(evt);
            }
        });

        txtNumeroB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNumeroB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtNumeroBStateChanged(evt);
            }
        });

        txtNumeroC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNumeroC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtNumeroCStateChanged(evt);
            }
        });

        lblEnunciadoB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEnunciadoB.setText("<html>x<sup>2</sup></html>");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("x +");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("= 0");

        lblDeltaFormula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDeltaFormula.setText("<html>&Delta;=</html>");

        lblNumeroB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumeroB.setForeground(new java.awt.Color(255, 0, 0));
        lblNumeroB.setText("B");

        lblFormulaB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFormulaB.setText("<html><sup>2</sup>-4.</html>");

        lblNumeroA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumeroA.setForeground(new java.awt.Color(255, 0, 0));
        lblNumeroA.setText("A");

        jLabel8.setText(".");

        lblNumeroC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumeroC.setForeground(new java.awt.Color(255, 0, 0));
        lblNumeroC.setText("C");

        btnCalcularDelta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCalcularDelta.setText("<html>Calcular &Delta;</html>");
        btnCalcularDelta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularDeltaActionPerformed(evt);
            }
        });

        lblDeltaResultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDeltaResultado.setText("<html>Valor de &Delta;=</html>");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Tipo = ");

        lblDelta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDelta.setForeground(new java.awt.Color(0, 0, 255));
        lblDelta.setText("jLabel9");

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(0, 0, 255));
        lblTipo.setText("jLabel10");

        javax.swing.GroupLayout painelResultadoLayout = new javax.swing.GroupLayout(painelResultado);
        painelResultado.setLayout(painelResultadoLayout);
        painelResultadoLayout.setHorizontalGroup(
            painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelResultadoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(lblDeltaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDelta)
                    .addComponent(lblTipo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelResultadoLayout.setVerticalGroup(
            painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelResultadoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeltaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDelta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblTipo))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtNumeroA, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEnunciadoB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumeroB, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumeroC, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCalcularDelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDeltaFormula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNumeroB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFormulaB, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNumeroA)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNumeroC)))))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(painelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnunciadoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeltaFormula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroB)
                    .addComponent(lblFormulaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroA)
                    .addComponent(jLabel8)
                    .addComponent(lblNumeroC))
                .addGap(30, 30, 30)
                .addComponent(btnCalcularDelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularDeltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularDeltaActionPerformed
       painelResultado.setVisible(true);
       //pegando os valores do spinner
       float numeroA = Float.parseFloat(txtNumeroA.getValue().toString());
       float numeroB = Float.parseFloat(txtNumeroB.getValue().toString());
       float numeroC = Float.parseFloat(txtNumeroC.getValue().toString());
       
       //calculando o Delta
       double delta = Math.pow(numeroB, 2) - 4 * numeroA * numeroC;
       
       //escrevendo o delta no programa
       //lblDelta.setText(Double.toString(delta));
       //formatando como o guanabara fez é bom por causa das casas decimais
       lblDelta.setText(String.format("%.1f", delta));
       //lógica para o texto do tipo
       if (delta >= 0 ){
           lblTipo.setText("Existem raízes reais.");
       } else {
           lblTipo.setText("Não existem raízes reais.");
       }
    }//GEN-LAST:event_btnCalcularDeltaActionPerformed

    private void txtNumeroAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtNumeroAStateChanged
        lblNumeroA.setText(txtNumeroA.getValue().toString());
    }//GEN-LAST:event_txtNumeroAStateChanged

    private void txtNumeroBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtNumeroBStateChanged
        lblNumeroB.setText(txtNumeroB.getValue().toString());
    }//GEN-LAST:event_txtNumeroBStateChanged

    private void txtNumeroCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtNumeroCStateChanged
        lblNumeroC.setText(txtNumeroC.getValue().toString());
    }//GEN-LAST:event_txtNumeroCStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEquacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEquacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEquacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEquacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEquacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularDelta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblDelta;
    private javax.swing.JLabel lblDeltaFormula;
    private javax.swing.JLabel lblDeltaResultado;
    private javax.swing.JLabel lblEnunciadoB;
    private javax.swing.JLabel lblFormulaB;
    private javax.swing.JLabel lblNumeroA;
    private javax.swing.JLabel lblNumeroB;
    private javax.swing.JLabel lblNumeroC;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel painelResultado;
    private javax.swing.JSpinner txtNumeroA;
    private javax.swing.JSpinner txtNumeroB;
    private javax.swing.JSpinner txtNumeroC;
    // End of variables declaration//GEN-END:variables
}
