/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

import java.awt.Font;
/**
 *
 * @author Felipe Dantas
 */
public class TelaAdivinhacao extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdivinhacao
     */
    public TelaAdivinhacao() {
        initComponents();
        lblNumeroPensado.setText("<html>Vou pensar em um valor entre 1 e 5, tente adivinhar!</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPalpite = new javax.swing.JSpinner();
        btnAdivinhar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNumeroPensado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPalpite.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(txtPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        btnAdivinhar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdivinhar.setText("Adivinhar");
        btnAdivinhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdivinharActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdivinhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mago150x150.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        lblNumeroPensado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNumeroPensado.setText("Qual número estou pensando?");
        lblNumeroPensado.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblNumeroPensado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 120, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balao-de-fala200x200.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 180));

        jLabel2.setText("Numero:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdivinharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdivinharActionPerformed
        //Gerar número para ser adivinhado
        int numeroPensado = (int) ( 1 + Math.random() * 5);
        
        //número palpite do usuario
        int palpite = Integer.parseInt(txtPalpite.getValue().toString());
        
        //comparando valores, tentei usar o equals deu problema, quando eu for comparar números tentarei usar o operador ==
        boolean adivinhou = (palpite == numeroPensado);
        
        //verificando qual fala será selecionada
        String falaDoSabio;
        String frase1 = "<html>Parabéns eu estava pensando nesse número.</html>";
        //Para dar certo eu preciso colocar o </html> depois do valor
        String frase2 = "<html>Você errou, eu estava pensando no número " + numeroPensado + ".</html>";
        //Integer.toString(numeroPensado)
        falaDoSabio = adivinhou ? frase1 : frase2 ;
        
        lblNumeroPensado.setFont(new Font("Arial Black", Font.PLAIN, 14));
        
        //Inserindo a fala do sabio na caixa de dialogo.
        lblNumeroPensado.setText(falaDoSabio);
    }//GEN-LAST:event_btnAdivinharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdivinhacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdivinhacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdivinhacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdivinhacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdivinhacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdivinhar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNumeroPensado;
    private javax.swing.JSpinner txtPalpite;
    // End of variables declaration//GEN-END:variables
}
